#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceGenerateBoundingBox cylinder.stl cylinderbox.stl 96e-6 192e-6 8e-7 8e-7 96e-6 96e-6

runApplication surfaceFeatureEdges cylinderbox.stl cylinder.fms -angle 30

runApplication cartesianMesh

runApplication checkMesh
